// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Text;
using MySql.Data.MySqlClient;
using System.Data;
namespace SimpleService
{
	public class MySQLHelper :IDisposable
	{
		#region Fields
		private string connectionString="Server=localhost;" +
			"Database=RapidRacing;" +
				"User ID=root;" +
				"Password=;" +
				"Pooling=false";
		private IDbConnection dbcon;
		private IDbCommand dbcmd;
		#endregion

		#region Properties
		public string ConnectionString{get;set;}

		#endregion

		#region  Ctors
		public MySQLHelper (){  }

		public MySQLHelper (string connectionStr)
		{
			this.connectionString=connectionStr;
		}

		#endregion

		public void ConnectDB()
		{
			dbcon = new MySqlConnection(connectionString);
			dbcon.Open();
			dbcmd = dbcon.CreateCommand();
		}

		public IDataReader ExecuteReader(string sql)
		{
			dbcmd.CommandText = sql;
			IDataReader reader = dbcmd.ExecuteReader();
			return reader;
		}

		public void Close()
		{
			try
			{
				dbcmd.Dispose();
				dbcmd = null;
				dbcon.Close();
				dbcon = null;
			}
			catch{}
		}

		#region IDisposable implementation

		public void Dispose ()
		{
			Close();
		}

		#endregion
	}
}

