// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MySql.Data.MySqlClient;
using System.Data;
using System.Text;
namespace SimpleService
{
	public class MySQL_Test
	{
		private MySQLHelper mySqlHelper=null;
		public MySQL_Test ()
		{
			mySqlHelper=new MySQLHelper();
		}

		public string Test()
		{
			string result="";
			mySqlHelper.ConnectDB();
			IDataReader reader=mySqlHelper.ExecuteReader("use test;" +
				"select * from user;");
			while(reader.Read()) 
			{
				int FirstName = (int) reader["userId"];
				string LastName = (string) reader["username"];
				result="id: " +
					FirstName + " username:" +  LastName;
			}
			reader.Close();
			reader=null;
			mySqlHelper.Close();
			return result;
		}
	}
}

