// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Threading;
using System.Text;
using System.Net.Sockets;
using System.Net;
using SimpleJSON;
namespace SimpleService
{
	public class ClientThread:IDisposable
	{
		#region Fields
		/// <summary>
		/// 初始值可以为空的哦，登录失败嘛
		/// </summary>
		private string userName;
		private Session _session;
		private Guid _guid;
		private bool isLogin=false;
		private Thread thread;

		#endregion
		#region Properties
		public Session _Session {
			get {
				return _session;
			}
			set {
				_session = value;
			}
		}
		/// <summary>
		/// 初始值可以为空的哦，登录失败嘛
		/// </summary>
		public string UserName {
			get {
				return userName;
			}
			private set {
				userName = value;
			}
		}

		public bool IsLogin {
			get {
				return isLogin;
			}
			set {
				isLogin = value;
			}
		}

		public Thread Thread {
			get {
				return thread;
			}
			private set {
				thread = value;
			}
		}

		#endregion

		#region Constructors
		public ClientThread ()
		{

		}

		public ClientThread (Session session,Thread thread,Guid guid)
		{
			this._session=session;
			this.thread=thread;
			this._guid=guid;
		}

		#endregion

		#region Method

		public void ThreadStart()
		{

		}

		public void ThreadStop()
		{

		}

		#endregion

		#region IDisposable implementation

		public void Dispose ()
		{
			this.ThreadStop();
			isLogin=false;
			userName=null;
			_session.Close();
			_session=null;
			_guid=Guid.Empty;
		}

		#endregion
	}
}

