// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections;
using System.Text;
using System.Net;
using System.Threading;
using System.Net.Sockets;

namespace SimpleService
{
	public class MySimpleService
	{
		private string host="127.0.0.1";
		private int port=8421;

		private Socket serviceSocket=null;
		private Dictionary<string ,Socket> clientSockets=null;

		public MySimpleService ()
		{
			clientSockets=new Dictionary<string, Socket>();
		}


		public void StartListen()
		{

			Socket serviceSocket=new Socket(AddressFamily.InterNetwork,SocketType.Stream,ProtocolType.Tcp);
//			serviceSocket.Bind
		}


		void Listen()
		{

		}




	}
}

